site_name: My Projects
nav:
  - Home: index.md
  - Snake Game: snake_game/snake.md
#
#
# Don't alter the following sections
#
#
theme:
  name: material
  logo: img/logo.gif
  favicon: img/logo.gif
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra_css.css
# extra_javascript:
#   - javascript/extra.js