site_name: My Projects
nav:
  - index.md
  - Overview: documentation_overview.md
  - Python:
    - python/python_projects.md
    - Game:
      - python/snake_game/snake.md
    - Scripts:
      - python/walk_dir/walk_dir.md
    - Nootebooks:
      - Highest movies grossing:
        - python/movies_grossing/movies.ipynb
        - python/movies_grossing/algorithms.ipynb
      - python/netflix/netflix_data_analisys.ipynb
    - Unit Tests:
      - python/unit_tests/unit_tests.md
  - Web:
    - Task App:
      - web/task_app/task_app.md
      - web/task_app/task_app_endpoints.md
    - web/weather_app/weather_app.md
    - web/notes_app/notes_app.md
    - web/book_tracker/book_tracker.md
    - Javascript Exercises:
      - web/js_exercises/multiplication_table.md
      - web/js_exercises/calculate.md
    - web/clock.md
  - C/C++:
    - C Exercises:
      - c_cpp_projects/c_exercises/discount_calculation.md
      - c_cpp_projects/c_exercises/ideal_weight.md
      - c_cpp_projects/c_exercises/operations.md
      - c_cpp_projects/c_exercises/personal_loan.md
      - c_cpp_projects/c_exercises/product_where_from.md
      - c_cpp_projects/c_exercises/swimmer_category.md
      - c_cpp_projects/c_exercises/gratification.md
      - c_cpp_projects/c_exercises/raise_and_classification.md
      - c_cpp_projects/c_exercises/raise_price.md
      - c_cpp_projects/c_exercises/show_biggest.md
      - c_cpp_projects/c_exercises/data_collection.md
      - c_cpp_projects/c_exercises/tic_tac_toe.md
    - c_cpp_projects/confectionery/confectionery.md
    - c_cpp_projects/service_provider/service_provider.md
  - C.E.:
    - ce/controle_de_estoque.md
    - ce/architecture.md
    - ce/app_overview.md
#
#
# Don't alter the following sections
#
#
repo_url: https://github.com/joaohb07/documentation
repo_name: documentation
edit_uri: ""
theme:
  name: material
  logo: img/logo.gif
  favicon: img/logo.gif
  icon:
    repo: fontawesome/brands/gitkraken
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
      theme: dark
extra_css:
  - stylesheets/extra_css.css
# extra_javascript:
#   - javascript/extra.js