site_name: My Projects
nav:
  - Home: index.md
  - Python:
    - Snake Game: python/snake_game/snake.md
    - Baseline Classification: python/baseline_classification/Baseline-Classification.ipynb
#
#
# Don't alter the following sections
#
#
repo_url: https://github.com/joaobotelho072002/joaobotelho072002.github.io
repo_name: joaobotelho072002/joaobotelho072002.github.io
edit_uri: ""
theme:
  name: material
  logo: img/logo.gif
  favicon: img/logo.gif
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - navigation.top
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
plugins:
  - mkdocs-jupyter:
      execute: True
      theme: dark
extra_css:
  - stylesheets/extra_css.css
# extra_javascript:
#   - javascript/extra.js